---
title: "Week 3 Assignment"
author: "Dan Brooks"
date: "February 7, 2016"
output: pdf_document
---

```{r Get_Information_From_GitHub}
#I am grabbing my data from my GitHub Repositories
library(RCurl)
ReadPopulation <- getURL("https://raw.githubusercontent.com/DanielBrooks39/IS607/master/Week%203/population.csv")
Population <- read.csv(text = ReadPopulation)

ReadTBInformation <- getURL("https://raw.githubusercontent.com/DanielBrooks39/IS607/master/Week%203/tb_Excel.csv")
TBInformation <- read.csv(text = ReadTBInformation, header = FALSE)

#I am giving names to the columns of the data frame
names(TBInformation) <- c("Country", "Year", "Sex", "Child", "Adult", "Elderly")

#The file had some (-1) in it so I converted anything that was negative to 0.
TBInformation$Child <- replace(TBInformation$Child, TBInformation$Child <= 0, 0)
TBInformation$Adult <- replace(TBInformation$Adult, TBInformation$Adult <= 0, 0)
TBInformation$Elderly <- replace(TBInformation$Elderly, TBInformation$Elderly <= 0, 0)
```

```{r Data_Manipulation}
#Subsetted the data by sex. One for Males and one for Females
Males <- subset(TBInformation, Sex == "male")
Females <- Males <- subset(TBInformation, Sex == "female")

#Found the total number of cases across all the age ranges
#that were taken (Child, Adult, and Elderly)
TotalCasesMale <- Males$Child + Males$Adult + Males$Elderly
TotalCasesFemale <- Females$Child + Females$Adult + Females$Elderly

#Give names to the subsetted data frame
Males_Country <- as.vector(as.character(Males$`Country`))
Males_Year <- as.vector(as.numeric(Males$`Year`))
Females_Country <- as.vector(as.character(Females$`Country`))
Females_Year <- as.vector(as.numeric(Females$`Year`))

#bind the the data frame that was subsetted by sex back together
#with the total cases added to it
Males_Info <- cbind.data.frame(Males_Country, Males_Year, TotalCasesMale, Population$population)
Females_Info <- cbind.data.frame(Females_Country, Females_Year, TotalCasesFemale, Population$population)

#Give names to the new data frame
names(Males_Info) <- c("Country", "Year", "Cases", "Population")
names(Females_Info) <- c("Country", "Year", "Cases", "Population")

#Calcluate the Rate at which TB spreads (Total Cases/Total Population)
#Multiply by 100 to make it a percentage
Male_Rate <- (Males_Info$Cases / (Males_Info$Population/10000)) 
Female_Rate <- (Females_Info$Cases / (Females_Info$Population/10000))

#Bind the COuntries, Year and Rate all together
Males_Info <- cbind.data.frame(Males_Info$Country, Males_Info$Year, Male_Rate)
Females_Info <- cbind.data.frame(Females_Info$Country, Females_Info$Year, Female_Rate)

#Give names to the Newly bound data frame
names(Males_Info) <- c("Country", "Year", "Rate (per 10,000 ppl)")
names(Females_Info) <- c("Country", "Year", "Rate (per 10,000 ppl)")

#Show the top 50 records in the Males and Female data frames
head(Males_Info, n = 50L)

head(Females_Info, n = 50L)
```

